// https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...


function fibonacciEvenSum(limit) {
    // A list containing the first two values is created and these two values are added together to form a Fibonacci sequence.
    let sum = 2;
    let fibonacci = [1,2];

    let i = 0;
    while (fibonacci[fibonacci.length - 1] < limit) {
        let add = fibonacci[i] + fibonacci[i + 1];
        fibonacci.push(add);

        // If it is within bounds and even, it is added to the array.
        if (fibonacci[fibonacci.length - 1] < limit) {
            if (add % 2 === 0) {
                sum += add;
            }
        }
        i ++;
    }

    return sum;
}

module.exports = {
    fibonacciEvenSum
}